# DO NOT EDIT THIS FILE!
#
# Python module KeyGen generated by omniidl

import omniORB
omniORB.updateModule("KeyGen")

# ** 1. Stub files contributing to this module
import keygen_idl

# ** 2. Sub-modules

# ** 3. End
